name: Mi-Git-tainer
env:
  Application_name: "myFlask"
  Package_name: "flask_deploy_ver_${{githab_sha}}"
on:
 push: 
  branches:
  - main

jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello world from testing job"
    - name: Execure few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Hello Message1"
        echo "Application_name: ${{ env.Application_name }}"


  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
   
    steps:
    - name: Print Hello Message if Deploy
      run: echo "Hello world from Deploy job"
    - name: Printing Deployment package
      run: echo "Deployment package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
